'use client';

import {
  Wheat,
  Info,
  HelpCircle,
  Cpu,
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  Lightbulb,
} from 'lucide-react';

export default function AboutPanel() {
  const sensorSpecs = [
    { name: 'SHT31 Temperature & Humidity', usage: 'Monitors ambient storage air condition to calculate mold development conditions.' },
    { name: 'BME688 VOC / Air Quality', usage: 'Detects Volatile Organic Compounds (VOCs) reflecting grain fermentation or microbial activity.' },
    { name: 'MH-Z19B CO₂ Sensor', usage: 'Identifies increased CO₂ levels signifying intense microbial respiration or insect infestation.' },
    { name: 'Grain Moisture Sensor', usage: 'Measures moisture contents inside the grain stack to recommend drying or aeration cycles.' },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      {/* Introduction Card */}
      <div className="silo-card animate-fade-in-up" style={{ padding: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '16px' }}>
          <div
            style={{
              width: '44px',
              height: '44px',
              borderRadius: '12px',
              background: 'linear-gradient(135deg, var(--silo-green), var(--silo-green-light))',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              boxShadow: '0 0 15px rgba(46, 125, 50, 0.2)',
            }}
          >
            <Wheat size={24} color="#fff" />
          </div>
          <div>
            <h3 style={{ fontSize: '1rem', fontWeight: 800 }}>About SILO Monitoring System</h3>
            <p style={{ fontSize: '0.75rem', color: 'var(--text-dim)' }}>Version 1.0.0 (Global Stable)</p>
          </div>
        </div>

        <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', lineHeight: 1.6, marginBottom: '16px' }}>
          <strong>SILO (Smart Storage for Safer Harvests)</strong> is a web-based monitoring system designed specifically for postharvest grain storage.
          The system receives real-time environmental data generated by custom ESP32 units installed inside storage bins, allowing operators to prevent postharvest losses caused by mold growth, dampness, and poor aeration.
        </p>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '12px' }}>
          <div style={{ padding: '14px', borderRadius: '8px', background: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
              <ShieldCheck size={16} color="var(--silo-green)" />
              <span style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-primary)' }}>Risk Prevention</span>
            </div>
            <p style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', lineHeight: 1.4 }}>
              Maintains grain storage quality by forecasting mold risks based on temperature, relative humidity, and grain moisture index.
            </p>
          </div>

          <div style={{ padding: '14px', borderRadius: '8px', background: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
              <Cpu size={16} color="var(--silo-green)" />
              <span style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-primary)' }}>Automated Aeration</span>
            </div>
            <p style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', lineHeight: 1.4 }}>
              Trigger ventilation fans or dehumidifying relays automatically as soon as mold risk limits exceed safety parameters.
            </p>
          </div>
        </div>
      </div>

      {/* Sensor Specifications Card */}
      <div className="silo-card animate-fade-in-up delay-100" style={{ padding: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
          <Info size={18} color="var(--silo-green)" />
          <h3 style={{ fontSize: '0.9rem', fontWeight: 700 }}>Recommended Sensors & Wiring</h3>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          {sensorSpecs.map((sensor, i) => (
            <div
              key={i}
              style={{
                display: 'flex',
                gap: '12px',
                padding: '12px',
                background: 'rgba(255,255,255,0.01)',
                borderRadius: '8px',
                borderLeft: '3px solid var(--silo-green)',
                borderRight: '1px solid var(--border-color)',
                borderTop: '1px solid var(--border-color)',
                borderBottom: '1px solid var(--border-color)',
              }}
            >
              <div style={{ flex: 1 }}>
                <span style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-primary)' }}>{sensor.name}</span>
                <p style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', marginTop: '4px', lineHeight: 1.4 }}>{sensor.usage}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* FAQ & Quick Guidelines */}
      <div className="silo-card animate-fade-in-up delay-200" style={{ padding: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
          <HelpCircle size={18} color="var(--silo-green)" />
          <h3 style={{ fontSize: '0.9rem', fontWeight: 700 }}>Quick System Guidelines</h3>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
          <div>
            <h4 style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '4px' }}>
              How is Mold Risk calculated?
            </h4>
            <p style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', lineHeight: 1.4 }}>
              The system calculates risk by cross-referencing Relative Humidity (RH), ambient air Temperature, and Grain moisture. If RH exceeds 75% and temperature is above 35°C, risk escalates rapidly.
            </p>
          </div>

          <div>
            <h4 style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '4px' }}>
              What happens in high mold conditions?
            </h4>
            <p style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', lineHeight: 1.4 }}>
              Once Mold Risk goes above 70%, the ESP32 automatically controls and turns ON the ventilation relay to reduce moisture. If it surges past 90%, critical red status switches on.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
